### ISSUE TITLE
Not valid HTML

### ISSUE THREAD

**Issue by jomo** [catc/simple-hint#1]
http://validator.w3.org/check

``` HTML
<!DOCTYPE HTML>
<html>
<head>
  <title>Test</title>
</head>
<body>
  <span simple-hint="your message goes here" class="hint-top">Top hint</span>
</body>
</html>
```

>  **Line 7, Column 62**: Attribute `simple-hint` not allowed on element span at this point.
> `<span simple-hint="your message goes here" class="hint-top">Top hint</span>`

---

I suggest using `data-hint` or `data-simple-hint`

**Comment by catc** [comment]
I'll change it this weekend.

**Comment by jomo** [comment]
Alternatively you could use

``` HTML
<span class="simple-hint hint-top" title="your message goes here">Foo Bar</span>
```
