### ISSUE TITLE
Host it on free CDN

### ISSUE THREAD

**Issue by siamkreative** [catc/simple-hint#3]
Hello Catalin,

I think it would be fantastic if you could host your plugin on CDNJS. It's reliable and fast. In my current project, only `simple-hint.min.css` is not hosted there actually. I would be grateful if you could host it there as well, and I think it'll benefit others too.

Here are the guidelines: https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library.

Lemme know if I can help.

Cheers

**Comment by jimaek** [comment]
Here you go http://www.jsdelivr.com/projects/simple-hint

**Comment by siamkreative** [comment]
Thanks @jimaek!

I'd like to host it on CDNJS, what do you think @catc ? Do you want me to help with this?

**Comment by catc** [comment]
@SiamKreative yeah, that'd be great. Lemme know if you need anything from me.

**Comment by siamkreative** [comment]
Sticking with JsDelivr for now...
