### ISSUE TITLE
Hint position even more advanced

### ISSUE THREAD

**Issue by liviuang** [catc/simple-hint#4]
Hi,

I think it would be great and complete to position the hint as follows:

![hint-position](https://cloud.githubusercontent.com/assets/295398/11239214/1c0d40a6-8df3-11e5-92fd-dd9497e524cc.jpg)

**Comment by liviuang** [comment]
This below will fix the bottom-right tip

```
// Bottom Position for elements on the Right Side of the Screen

[class*="hint-bottom-right"]:after {
  right: 0;
  left: auto;
  -webkit-transform: translateX(0);
  -ms-transform: translateX(0);
  transform: translateX(0);
}

[class*="hint-bottom-right"]:before {
  right: 0;
  margin-right: 5px;
}
```

**Comment by catc** [comment]
Did you check if it broke the animations/transitions? I don't really have time to update it with new positions, but if you put in a pull request I'll definitely look at it.

**Comment by catc** [comment]
Feature added in https://github.com/catc/simple-hint/releases/tag/3.0.0. Closing.
